Updated to new standards

diff --git a/snippet/setup b/snippet/setup
--- a/snippet/setup
+++ b/snippet/setup
@@ -1,94 +1,94 @@
-_VERSION_=""
-_PROJECT_="${0##*/}"
+CurVer=''
+Progrm=${0##*/}
 
-FAIL(){
+Err(){
 	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
+	[ $1 -gt 0 ] && exit $1
 }
 
-DOM="https://github.com"
+Domain='https://github.com'
 
-USAGE(){
+Usage(){
 	while read; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            ${_PROJECT_^^} ($_VERSION_)
+		            ${Progrm^^} ($CurVer)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
 		            Dummy description for this template.
 
-		SYNTAX:     $_PROJECT_ [OPTS]
+		SYNTAX:     $Progrm [OPTS]
 
 		OPTS:       --help|-h|-?            - Displays this help information.
 		            --version|-v            - Output only the version datestamp.
 		            --quiet|-q              - Runs in quiet mode. Errors still output.
-		            --update|-U             - Check for updates to $_PROJECT_.
-		            --debug|-D              - Enables the built-in bash debugging.
+		            --update|-U             - Check for updates to $Progrm.
+		            --debug|-D              - Enables the built-in Bash debugging.
 
-		SITE:       $DOM/terminalforlife/Extra
+		SITE:       $Domain/terminalforlife/Extra
 	EOF
 }
 
 while [ "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
-			USAGE; exit 0 ;;
+			Usage; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$_VERSION_"; exit 0 ;;
+			printf "%s\n" "$CurVer"; exit 0 ;;
 		--quiet|-q)
-			BEQUIET='true' ;;
+			BeQuiet='true' ;;
 		--debug|-D)
-			DEBUGME='true' ;;
+			DebugMe='true' ;;
 		--update|-U)
-			UPDATE='true' ;;
+			DoUpdate='true' ;;
 		#-*)
-		#	FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
+		#	Err 1 $LINENO 'Incorrect argument(s) specified.' ;;
 		#*)
 		#	break ;;
 		*)
-			FAIL 1 $LINENO "Incorrect argument(s) specified." ;;
+			Err 1 $LINENO 'Incorrect argument(s) specified.' ;;
 	esac
 	shift
 done
 
-declare -i DEPCOUNT=0
-for DEP in :; {
-	if ! type -fP "$DEP" > /dev/null 2>&1; then
-		FAIL 0 "$LINENO" "Dependency '$DEP' not met."
-		DEPCOUNT+=1
+declare -i DepCount=0
+for Dep in :; {
+	if ! type -fP "$Dep" > /dev/null 2>&1; then
+		Err 0 $LINENO "Dependency '$Dep' not met."
+		DepCount+=1
 	fi
 }
 
-[ $DEPCOUNT -eq 0 ] || exit 1
+[ $DepCount -eq 0 ] || exit 1
 
-if [ "$UPDATE" == "true" ]; then
+if [ "$DoUpdate" == 'true' ]; then
 	if ! type -fP wget > /dev/null 2>&1; then
-		FAIL 1 "$LINENO" "Dependency 'wget' not met."
+		Err 1 $LINENO "Dependency 'wget' not met."
 	fi
 
-	VERSION_URL="$DOM/terminalforlife/Extra/raw/master/versions"
-	while IFS='=' read -a LINE; do
-		if  [ "${LINE[0]}" == "$_PROJECT_" ]; then
-			LATEST="${LINE[1]}"
-			if [[ "${LATEST//-}" =~ ^[0-9]{8}$ ]]; then
-				if [ ${LATEST//-} -gt ${_VERSION_//-} ]; then
-					while read -r; do
+	VerURL="$Domain/terminalforlife/Extra/raw/master/versions"
+	while IFS='=' read -a CurLine; do
+		if  [ "${CurLine[0]}" == "$Progrm" ]; then
+			NewVer=${CurLine[1]}
+			if [[ ${NewVer//-} =~ ^[0-9]{8}$ ]]; then
+				if [ ${NewVer//-} -gt ${CurVer//-} ]; then
+					while read; do
 						printf "%s\n" "$REPLY"
 					done <<-EOF
-						New version available:    $LATEST
-						Current version:          $_VERSION_
+						New version available:    $NewVer
+						Current version:          $CurVer
 					EOF
 				fi
 			else
-				FAIL 1 "$LINENO" "Failed to check for available updates."
+				Err 1 $LINENO 'Failed to check for available updates.'
 			fi
 		fi
-	done <<< "$(wget -q "$VERSION_URL" -O -)"
+	done <<< "$(wget -qO - "$VerURL")"
 
 	exit 0
 fi
 
-#[ $UID -eq 0 ] && FAIL 1 "$LINENO" "Root access is required."
+#[ $UID -eq 0 ] || Err 1 $LINENO 'Root access is required.'
 
-[ "$BEQUIET" == "true" ] && exec > /dev/null
-[ "$DEBUGME" == "true" ] && set -x
+[ "$BeQuiet" == 'true' ] && exec > /dev/null
+[ "$DebugMe" == 'true' ] && set -x
