Update snippets

diff --git a/source/snippet/bsetup b/source/snippet/bsetup
--- a/source/snippet/bsetup
+++ b/source/snippet/bsetup
@@ -1,17 +1,19 @@
+set -e
 . /usr/lib/tflbp-sh/Err
 . /usr/lib/tflbp-sh/ChkDep
+set +e
 
 CurVer=''
 Progrm=${0##*/}
 
 Usage(){
 	while read -r CurLine; do
-		printf "%b\n" "$CurLine"
+		printf '%b\n' "$CurLine"
 	done <<EOF
 		\r            : ($CurVer)
 		\r            Written by terminalforlife (terminalforlife@yahoo.com)
 
-		\r            Dummy description for this template.
+		\r            ...
 
 		\rSYNTAX:     $Progrm [OPTS]
 
@@ -26,21 +28,21 @@ while [ "$1" ]; do
 		--help|-h|-\?)
 			Usage; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$CurVer"; exit 0 ;;
+			printf '%s\n' "$CurVer"; exit 0 ;;
 		--quiet|-q)
 			BeQuiet='true' ;;
 		#-*)
-		#	Err 1 'Incorrect argument(s) specified.' ;;
+		#	Err 1 'Incorrect option(s) specified.' ;;
 		#*)
 		#	break ;;
 		*)
-			Err 1 'Incorrect argument(s) specified.' ;;
+			Err 1 'Incorrect option(s) specified.' ;;
 	esac
 	shift
 done
 
-ChkDep :
+ChkDep id
 
-#[ $UID -eq 0 ] || Err 1 'Root access is required.'
+#[ `id -u` -eq 0 ] || Err 1 'Root access is required.'
 
-[ "$BeQuiet" == 'true' ] && exec > /dev/null
+[ "$BeQuiet" = 'true' ] && exec 1> /dev/null
diff --git a/source/snippet/setup b/source/snippet/setup
--- a/source/snippet/setup
+++ b/source/snippet/setup
@@ -1,12 +1,12 @@
+set -e
+. /usr/lib/tflbp-sh/Err
+. /usr/lib/tflbp-sh/ChkDep
+set +e
+
 CurVer=''
 Progrm=${0##*/}
 
-Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -gt 0 ] && exit $1
-}
-
-Domain='https://github.com'
+Domain='https://github.com/terminalforlife/Extra'
 
 Usage(){
 	while read; do
@@ -15,7 +15,7 @@ Usage(){
 		            ${Progrm^^} ($CurVer)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
-		            Dummy description for this template.
+		            ...
 
 		SYNTAX:     $Progrm [OPTS]
 
@@ -25,7 +25,7 @@ Usage(){
 		            --update|-U             - Check for updates to $Progrm.
 		            --debug|-D              - Enables the built-in Bash debugging.
 
-		SITE:       $Domain/terminalforlife/Extra
+		SITE:       $Domain
 	EOF
 }
 
@@ -34,7 +34,7 @@ while [ "$1" ]; do
 		--help|-h|-\?)
 			Usage; exit 0 ;;
 		--version|-v)
-			printf "%s\n" "$CurVer"; exit 0 ;;
+			printf '%s\n' "$CurVer"; exit 0 ;;
 		--quiet|-q)
 			BeQuiet='true' ;;
 		--debug|-D)
@@ -42,30 +42,18 @@ while [ "$1" ]; do
 		--update|-U)
 			DoUpdate='true' ;;
 		#-*)
-		#	Err 1 $LINENO 'Incorrect argument(s) specified.' ;;
+		#	Err 1 'Incorrect option(s) specified.' ;;
 		#*)
 		#	break ;;
 		*)
-			Err 1 $LINENO 'Incorrect argument(s) specified.' ;;
+			Err 1 'Incorrect option(s) specified.' ;;
 	esac
 	shift
 done
 
-declare -i DepCount=0
-for Dep in :; {
-	if ! type -fP "$Dep" > /dev/null 2>&1; then
-		Err 0 $LINENO "Dependency '$Dep' not met."
-		DepCount+=1
-	fi
-}
-
-[ $DepCount -eq 0 ] || exit 1
+ChkDep wget
 
 if [ "$DoUpdate" == 'true' ]; then
-	if ! type -fP wget > /dev/null 2>&1; then
-		Err 1 $LINENO "Dependency 'wget' not met."
-	fi
-
 	VerURL="$Domain/terminalforlife/Extra/raw/master/versions"
 	while IFS='=' read -a CurLine; do
 		if  [ "${CurLine[0]}" == "$Progrm" ]; then
@@ -73,14 +61,14 @@ if [ "$DoUpdate" == 'true' ]; then
 			if [[ ${NewVer//-} =~ ^[0-9]{8}$ ]]; then
 				if [ ${NewVer//-} -gt ${CurVer//-} ]; then
 					while read; do
-						printf "%s\n" "$REPLY"
+						printf '%s\n' "$REPLY"
 					done <<-EOF
 						New version available:    $NewVer
 						Current version:          $CurVer
 					EOF
 				fi
 			else
-				Err 1 $LINENO 'Failed to check for available updates.'
+				Err 1 'Failed to check for available updates.'
 			fi
 		fi
 	done <<< "$(wget -qO - "$VerURL")"
@@ -88,7 +76,7 @@ if [ "$DoUpdate" == 'true' ]; then
 	exit 0
 fi
 
-#[ $UID -eq 0 ] || Err 1 $LINENO 'Root access is required.'
+#[ $UID -eq 0 ] || Err 1 'Root access is required.'
 
 [ "$BeQuiet" == 'true' ] && exec > /dev/null
 [ "$DebugMe" == 'true' ] && set -x
