Update snippets

diff --git a/source/snippet/setup b/source/snippet/setup
--- a/source/snippet/setup
+++ b/source/snippet/setup
@@ -8,7 +8,7 @@
 #
 # Dependencies:
 #
-#   bash (>= 4.3-14)
+#   bash (>= 4.4.20)
 #------------------------------------------------------------------------------
 
 CurVer=''
@@ -26,11 +26,11 @@ Usage(){
 }
 
 Err(){
-	printf 'ERROR: %s\n' "$2" 1>&2
-	[ $1 -gt 0 ] && exit $1
+	printf 'Err: %s\n' "$2" 1>&2
+	(( $1 > 0 )) && exit $1
 }
 
-while [ "$1" ]; do
+while [ -n "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
 			Usage; exit 0 ;;
@@ -54,6 +54,6 @@ for Dep in :; do
 	fi
 done
 
-[ $DepCount -gt 0 ] && exit 1
+(( DepCount > 0 )) && exit 1
 
-#[ $UID -eq 0 ] || Err 1 'Root access is required.'
+#(( UID == 0 )) || Err 1 'Root access is required.'
